<<<<<<< HEAD
# Generated by Django 4.2.9 on 2026-02-02 03:56
=======
# Generated by Django 4.2.9 on 2026-02-02 17:11
>>>>>>> 08392c1 (test 완료)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ 목록',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('status', models.CharField(choices=[('PENDING', '승인'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '답변완료')], default='PENDING', max_length=20, verbose_name='상태')),
                ('is_read', models.BooleanField(default=False, verbose_name='열람 여부')),
                ('admin_response', models.TextField(blank=True, verbose_name='관리자 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='문의 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
